#! /bin/bash

# This script requires the tool jq

# generate master key

newWallet58=$(node build/wallet.js new | sed 's/"//g')
echo -n $newWallet58 > master58.key

# derive a hardened public key
echo "{ \"wallet58\": \"$newWallet58\", \"paths\": [ \"m/0'\" ] }" \
  | node build/wallet.js derive-pubkey \
  | jq -rj '.[0]' > wallet58.key


# setup the database

cat database/init.sql | sqlite3 database.db
cat database/01.up.sql | sqlite3 database.db

# create the session counter

echo 0 > session.dat
